export const AUTHENTICATE           = 'AUTHENTICATE';
export const DEAUTHENTICATE         = 'DEAUTHENTICATE';
export const REAUTHENTICATE         = 'REAUTHENTICATE';

export const EMAIL_LOGIN_INFORMATION    = 'EMAIL_LOGIN_INFORMATION';
export const PASSWORD_LOGIN_INFORMATION = 'PASSWORD_LOGIN_INFORMATION';

export const ADD_IMAGE_LIST ='ADD_IMAGE_LIST'

